### ISSUE TITLE
v0.13.2.0-gentoo segfault on gentoo-hardened using multi-wallet functionality

### ISSUE THREAD

**Issue by grubles** [bitcoinknots/bitcoin#3]
Built with the following USE flags:

`net-p2p/bitcoin-qt wallet qt5 ljr qrcode `

gcc:

```$ gcc --version
gcc (Gentoo Hardened 4.9.4 p1.0, pie-0.6.4) 4.9.4
```
uname -a
```
Linux localhost 4.7.10-hardened #2 SMP PREEMPT Thu Dec 15 15:49:07 EST 2016 x86_64 AMD Phenom(tm) II X6 1090T Processor AuthenticAMD GNU/Linux
```
dmesg:
```[2441401.344952] bitcoin-qt[14637]: segfault at 56ecf593c8 ip 000003b3c697b43c sp 000003d953f0e8b0 error 4 in libQt5Core.so.5.6.2[3b3c671f000+4e9000]
[2441401.344983] grsec: Segmentation fault occurred at 00000056ecf593c8 in /usr/bin/bitcoin-qt[bitcoin-qt:14637] uid/euid:1000/1000 gid/egid:1000/1000, parent /bin/bash[bash:14633] uid/euid:1000/1000 gid/egid:1000/1000
[2441401.345906] grsec: denied resource overstep by requesting 4096 for RLIMIT_CORE against limit 0 for /usr/bin/bitcoin-qt[bitcoin-qt:14637] uid/euid:1000/1000 gid/egid:1000/1000, parent /bin/bash[bash:14633] uid/euid:1000/1000 gid/egid:1000/1000
[2441642.920006] bitcoin-qt[14815]: segfault at 8a66973a4b ip 000003cb15d3843c sp 000003d8698d1d20 error 4 in libQt5Core.so.5.6.2[3cb15adc000+4e9000]
[2441642.920027] grsec: Segmentation fault occurred at 0000008a66973a4b in /usr/bin/bitcoin-qt[bitcoin-qt:14815] uid/euid:1000/1000 gid/egid:1000/1000, parent /bin/bash[bash:14812] uid/euid:1000/1000 gid/egid:1000/1000
[2441642.920188] grsec: denied resource overstep by requesting 4096 for RLIMIT_CORE against limit 0 for /usr/bin/bitcoin-qt[bitcoin-qt:14815] uid/euid:1000/1000 gid/egid:1000/1000, parent /bin/bash[bash:14812] uid/euid:1000/1000 gid/egid:1000/1000
```

associated debug.log output:

```2017-01-13 22:04:07 GUI: Platform customization: "other"
2017-01-13 22:04:07 GUI: PaymentServer::LoadRootCAs: Loaded  157  root certificates
2017-01-13 22:04:07 GUI: QObject::connect: No such slot RPCConsole::test() in qt/rpcconsole.cpp:909
2017-01-13 22:04:07 GUI: QObject::connect:  (receiver name: 'RPCConsole')
```

With two wallets configured in bitcoin.conf, -qt runs well. However, once a third wallet is added to bitcoin.conf, the above happens.

**Comment by grubles** [comment]
backtrace (with three wallets):
```#0  0x000003fff5d2343c in ?? () from /usr/lib64/libQt5Core.so.5
#1  0x000003fff5d2a0dc in ?? () from /usr/lib64/libQt5Core.so.5
#2  0x000003fff69a6f04 in QTableView::setSortingEnabled(bool) () from /usr/lib64/libQt5Widgets.so.5
#3  0x000002aaaac397f6 in TransactionView::setModel(WalletModel*) ()
#4  0x000002aaaabd713e in WalletView::setWalletModel(WalletModel*) ()
#5  0x000002aaaabc1537 in WalletFrame::addWallet(QString const&, WalletModel*) ()
#6  0x000002aaaab436e1 in BitcoinGUI::addWallet(QString const&, WalletModel*) ()
#7  0x000002aaaab31246 in BitcoinApplication::initializeResult(int) ()
#8  0x000003fff5d8d28a in QObject::event(QEvent*) () from /usr/lib64/libQt5Core.so.5
#9  0x000003fff66a3f6d in QApplication::event(QEvent*) () from /usr/lib64/libQt5Widgets.so.5
#10 0x000003fff66a0cf4 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib64/libQt5Widgets.so.5
#11 0x000003fff66a5c96 in QApplication::notify(QObject*, QEvent*) () from /usr/lib64/libQt5Widgets.so.5
#12 0x000003fff5d5b550 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /usr/lib64/libQt5Core.so.5
#13 0x000003fff5d5e1ca in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) ()
   from /usr/lib64/libQt5Core.so.5
#14 0x000003fff5db7036 in ?? () from /usr/lib64/libQt5Core.so.5
#15 0x000003fff18c1423 in g_main_context_dispatch () from /usr/lib64/libglib-2.0.so.0
#16 0x000003fff18c1728 in ?? () from /usr/lib64/libglib-2.0.so.0
#17 0x000003fff18c1831 in g_main_context_iteration () from /usr/lib64/libglib-2.0.so.0
#18 0x000003fff5db70d3 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
   from /usr/lib64/libQt5Core.so.5
#19 0x000003fff5d598c2 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib64/libQt5Core.so.5
#20 0x000003fff5d6296b in QCoreApplication::exec() () from /usr/lib64/libQt5Core.so.5
#21 0x000002aaaab20eee in main ()
```

**Comment by luke-jr** [comment]
Is this still an issue?
